default:
  outputs:
    pro:
      type: snowflake
      account: kk91392.eu-west-3.aws
      user: juanma76854
      password: Real madrid 1
      role: ACCOUNTADMIN
      database: ALUMNO11_DEV_SILVER_DB
      warehouse: COMPUTE_WH
      schema: ALUMNO11
  target: pro

